services:
  windows:
    image: dockurr/windows
    ports:
      - "6080:6080"
    environment:
      RAM_SIZE: "16G"
      CPU_CORES: "16"
      DISK_SIZE: "500G"
    volumes:
      - persistent_data:/data
    devices:
      - /dev/dri:/dev/dri
volumes:
  persistent_data:
